version: 2.1
jobs:
  mobsf_scan:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            git clone https://github.com/cyberkru/mobsf-dojo.git
            cd mobsf-dojo
            cp ~/repo/InsecureBankv2.apk ./scan/
            TARGET_PATH='./InsecureBankv2.apk' DOJOKEY=${DOJOKEY} DOJOIP=${DOJOIP}  PRODNAME='InsecureBankv2' docker-compose up --build --exit-code-from scan
workflows:
  build_test_deploy:
    jobs:
      - mobsf_scan:
          context:
          - Scan_Env